export const MONEY_IN_SAVE = 'MONEY_IN_SAVE';
export const EDIT_MONEY_IN = 'EDIT_MONEY_IN';
export const SAVE_MONEY_OUT_DETAILS ="SAVE_MONEY_OUT_DETAILS";
export const SAVE_MONEY_OUT_LOAN_DETAILS ="SAVE_MONEY_OUT_LOAN_DETAILS";
export const SAVE_MONEY_OUT_GENERAL_DETAILS ="SAVE_MONEY_OUT_GENERAL_DETAILS";


export const EDIT_MONEY_OUT_LOAN_DETAILS ="EDIT_MONEY_OUT_LOAN_DETAILS";
export const EDIT_MONEY_OUT_DETAILS ="EDIT_MONEY_OUT_DETAILS";
export const CALCULATE_SUMMARY = 'CALCULATE_SUMMARY';
export const CALCULATE_SAVINGS = 'CALCULATE_SAVINGS';
